[package]
name = "actix-gcd"
version = "0.1.0"
edition = "2021"
authors = ["vladimir vankov vladimirvankovvankov@gmail.com"]

[dependencies]
actix-web = "4.8.0"
serde = { version = "1.0", features = ["derive"] }
